### ISSUE TITLE
Перенести параметры подключения в другой класс

### ISSUE THREAD

**Issue by hariuc** [Nana-wd/FotoGalery#2]
Необходимо перенести параметры подключения в другой класс.  Например класс DataBaseConnect
В данном классе будет один статический метод в его параметрах будут указаны параметры подключения, сервер, логин , пароль и база данных. Метод данного класса будет возвращать или подключение или выбрасывать Исключение.

Для того чтобы вбросить исключение нужно воспользоваться ключевым словом throw.  (Разбери работу с исключениями) и затем поймать блоком try/catch

**Comment by Nana-wd** [comment]
https://github.com/Nana-wd/FotoGalery/pull/10

**Comment by hariuc** [comment]
Принято
